language: node_js
cache: npm
node_js: 8

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

after_success:
  - npx semantic-release
  - npm run coverage:upload
